### PR TITLE
Fix wrong image dimensions in Media Browser #modxbughunt

### LINKED ISSUE #15255: Wrong image dimensions in the media browser
### Summary
The media browser shows the wrong image dimensions.

### Step to reproduce
Upload an image bigger then 800 pixels in the media browser the media browser, the image dimensions on the right panel displays the wrong image size. 

I have an image with the 1920x700 size, the media browser displays 800x292 pixels.

### Environment
MODX 3

Media browser size:
Schermafbeelding 2020-09-21 om 10 28 49

Real size:
Schermafbeelding 2020-09-21 om 10 29 49

### PR DESCRIPTION
**Pull request by wax100**
### What does it do?
Show correct original imge size

### Why is it needed?
To fix bug #15255

### How to test
Install modx & upload image bigger then 800*800px

### CODE REVIEW

File: core/src/Revolution/Sources/modMediaSource.php [hunk 1]
```diff
@@ -1908,6 +1909,8 @@ protected function buildFileBrowserViewList($path, $ext, $image_extensions, $bas
             'sid' => $this->get('id'),
             'name' => array_pop(explode(DIRECTORY_SEPARATOR, $path)),
             'cls' => 'icon-' . $ext,
+            'original_width' => $original['width'],
+            'original_height' =>$original['height'],
```
Comment (JoshuaLuckers) [inline core/src/Revolution/Sources/modMediaSource.php]:
```suggestion
            'original_height' => $original['height'],
```

File: manager/assets/modext/widgets/media/modx.browser.js [hunk 2]
```diff
@@ -41,7 +41,7 @@ MODx.browser.View = function(config) {
         ,id: this.ident
         ,fields: [
             {name: 'name', sortType: Ext.data.SortTypes.asUCString}
-            ,'cls','url','relativeUrl','fullRelativeUrl','image','image_width','image_height','thumb','thumb_width','thumb_height','pathname','pathRelative','ext','disabled','preview'
+            ,'cls','url','relativeUrl','fullRelativeUrl','image','original_width', 'original_height','image_width','image_height','thumb','thumb_width','thumb_height','pathname','pathRelative','ext','disabled','preview'
```
Comment (JoshuaLuckers) [inline manager/assets/modext/widgets/media/modx.browser.js]:
```suggestion
            ,'cls','url','relativeUrl','fullRelativeUrl','image','original_width','original_height','image_width','image_height','thumb','thumb_width','thumb_height','pathname','pathRelative','ext','disabled','preview'
```

**Review by JoshuaLuckers — CHANGES_REQUESTED** [review]

**Review by Ibochkarev — APPROVED** [review]
Before
2021-03-05 15-45-04 MODX Browser   MODX Revolution - Google Chrome

After
2021-03-05 15-47-18 MODX Browser   MODX Revolution - Google Chrome

**Review by JoshuaLuckers — APPROVED** [review]
