### PR TITLE
Fix "Undefined array key" warnings in modPhpThumb

### LINKED ISSUE #16340: MODX 3 modPhpThumb -> PHP warning: Undefined array key ...
### Summary
Then upload pictures via media browser get a lot of modPhpThumb.php warnings
Refer to my old Issue [16113](https://github.com/modxcms/revolution/issues/16113) to isolate the issue

### Step to reproduce
- new MODX 3.0.0 installation on localhost without having installed any extras
- updated to MODX 3.0.2
- upload pictures via media browser

### Error Log
```
/core/src/Revolution/modPhpThumb.php : 335) PHP warning: Undefined array key "sia"
/core/src/Revolution/modPhpThumb.php : 335) PHP warning: Undefined array key "down"
/core/src/Revolution/modPhpThumb.php : 337) PHP warning: Undefined array key "down"
/core/src/Revolution/modPhpThumb.php : 339) PHP warning: Undefined array key "down"
/core/src/Revolution/modPhpThumb.php : 305) PHP warning: Undefined array key "HTTP_IF_MODIFIED_SINCE"
```

### Observed behavior
- no errors with MODX 2.8.3 (PHP 7.4.16) on the same Linux System about two months ago
- therefore I am not sure if it is a MODX 3.0.x or/and a PHP 8.1.3 problem

### Expected behavior
no warnings in Error Log after uploading pictures

#### Trying to fix that in ../core/src/Revolution/modPhpThumb.php (near line 305 and 335 via isset function to prevent it)
[pull request 16341](https://github.com/modxcms/revolution/pull/16341)

```
            header('Last-Modified: ' . gmdate('D, d M Y H:i:s', $nModified) . ' GMT');
#          Fix PHP warning: Undefined array key "HTTP_IF_MODIFIED_SINCE"
//            if (@$_SERVER['HTTP_IF_MODIFIED_SINCE'] && ($nModified == strtotime($_SERVER['HTTP_IF_MODIFIED_SINCE'])) && @$_SERVER['SERVER_PROTOCOL']) {
//               header($_SERVER['SERVER_PROTOCOL'] . ' 304 Not Modified');
//              exit;
//            }
               if (isset($_SERVER['HTTP_IF_MODIFIED_SINCE']) && ($nModified == strtotime($_SERVER['HTTP_IF_MODIFIED_SINCE'])) && isset($_SERVER['SERVER_PROTOCOL'])) {
                  header($_SERVER['SERVER_PROTOCOL'] . ' 304 Not Modified');
               exit;
               }

            $getimagesize = @getimagesize($this->cache_filename);
            if ($getimagesize) {
                header('Content-Type: ' . phpthumb_functions::ImageTypeToMIMEtype($getimagesize[2]));
            } elseif (preg_match('#\.ico$#i', $this->cache_filename)) {
                header('Content-Type: image/x-icon');
            }
            if (!$this->config_cache_force_passthru && preg_match('#^' . preg_quote($nice_docroot, '/') . '(.*)$#',
                    $nice_cachefile, $matches)) {
                header('Location: ' . dirname($matches[1]) . '/' . urlencode(basename($matches[1])));
            } else {
                @readfile($this->cache_filename);
            }
            session_write_close();
            exit;

        }

        return true;
    }

    public function SendSaveAsFileHeaderIfNeeded()
    {
        if (headers_sent()) {
            return false;
        }

//         $downloadfilename = phpthumb_functions::SanitizeFilename(@$_GET['sia'] ? $_GET['sia'] : (@$_GET['down'] ? $_GET['down'] : 'phpThumb_generated_thumbnail' . (@$_GET['f'] ? $_GET['f'] : 'jpg')));
#         Fix PHP warning: Undefined array key "sia" and "down"
if (isset($_GET['sia'])) {
    $downloadfilename = phpthumb_functions::SanitizeFilename($_GET['sia']);
} elseif (isset($_GET['down'])) {
    $downloadfilename = phpthumb_functions::SanitizeFilename($_GET['down']);
} else {
    $downloadfilename = 'phpThumb_generated_thumbnail' . (isset($_GET['f']) ? $_GET['f'] : 'jpg');
}
//        if (@$downloadfilename) {
//            $this->DebugMessage('SendSaveAsFileHeaderIfNeeded() sending header: Content-Disposition: ' . (@$_GET['down'] ? 'attachment' : 'inline') . '; filename="' . $downloadfilename . '"',
//                __FILE__, __LINE__);
//            header('Content-Disposition: ' . (@$_GET['down'] ? 'attachment' : 'inline') . '; filename="' . $downloadfilename . '"');
//        }

if (isset($downloadfilename)) {
    if (isset($_GET['down'])) {
        $this->DebugMessage('SendSaveAsFileHeaderIfNeeded() sending header: Content-Disposition: attachment; filename="' . $downloadfilename . '"', __FILE__, __LINE__);
        header('Content-Disposition: attachment; filename="' . $downloadfilename . '"');
    } else {
        $this->DebugMessage('SendSaveAsFileHeaderIfNeeded() sending header: Content-Disposition: inline; filename="' . $downloadfilename . '"', __FILE__, __LINE__);
        header('Content-Disposition: inline; filename="' . $downloadfilename . '"');
    }
}
        return true;
    }
```

### Environment
- MODX Revolution 3.0.2-pl (traditional)
- System Linux 5.15.28-1-MANJARO (based on Arch)
- Apache/2.4.52 (Unix) PHP/8.1.3
- mysql: 10.7.3-MariaDB (database charset: utf8mb4)

### PR DESCRIPTION
**Pull request by jolichter**
Fix PHP warning: "undefined array key ..."  HTTP_IF_MODIFIED_SINCE, sia and down

### What does it do?
Prevents 3 modPhpThumb.php warnings when uploading files via the media browser

### Why is it needed?
no PHP warnings in MODX error log

### How to test
Describe how to test the changes you made.

### Related issue(s)/PR(s)
Please also refer to [16340](https://github.com/modxcms/revolution/issues/16340)

### CODE REVIEW

**Comment by jolichter** [comment]
Gesendet: Montag, 26. Dezember 2022 um 20:22 Uhr
Von: "cla-bot[bot]" ***@***.***>
An: "modxcms/revolution" ***@***.***>
Cc: "Jo Lichter" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [modxcms/revolution] Update modPhpThumb.php (PR #16341)


 

Thank you for your contribution! Before your pull request can be reviewed, please sign the MODX Contributor License Agreement (CLA). This is to make sure MODX has your written permission to distribute projects containing your contributions under the appropriate license.

Please make sure the CLA has been signed for GitHub user(s): @jolichter

Once you've signed, please reply with @cla-bot check to verify and update the status of this pull request.

**Review by JoshuaLuckers — APPROVED** [review]

**Review by JoshuaLuckers — APPROVED** [review]

File: core/src/Revolution/modPhpThumb.php [hunk 1]
```diff
@@ -302,10 +302,11 @@ public function RedirectToCachedFile()
             $this->SendSaveAsFileHeaderIfNeeded();
 
             header('Last-Modified: ' . gmdate('D, d M Y H:i:s', $nModified) . ' GMT');
-            if (@$_SERVER['HTTP_IF_MODIFIED_SINCE'] && ($nModified == strtotime($_SERVER['HTTP_IF_MODIFIED_SINCE'])) && @$_SERVER['SERVER_PROTOCOL']) {
-                header($_SERVER['SERVER_PROTOCOL'] . ' 304 Not Modified');
-                exit;
-            }
+            # Fix PHP warning: Undefined array key "HTTP_IF_MODIFIED_SINCE"
+               if (isset($_SERVER['HTTP_IF_MODIFIED_SINCE']) && ($nModified == strtotime($_SERVER['HTTP_IF_MODIFIED_SINCE'])) && isset($_SERVER['SERVER_PROTOCOL'])) {
```
Comment (smg6511) [inline core/src/Revolution/modPhpThumb.php]: You can simplify this just a bit, consider:

```suggestion

            if (isset($_SERVER['HTTP_IF_MODIFIED_SINCE'], $_SERVER['SERVER_PROTOCOL']) && $nModified === strtotime($_SERVER['HTTP_IF_MODIFIED_SINCE'])) {
```

File: core/src/Revolution/modPhpThumb.php [hunk 2]
```diff
@@ -332,13 +333,25 @@ public function SendSaveAsFileHeaderIfNeeded()
...
+   
+    # Fix PHP warning: "Undefined array key down"
+    if (isset($downloadfilename)) {
+        if (isset($_GET['down'])) {
+            $this->DebugMessage('SendSaveAsFileHeaderIfNeeded() sending header: Content-Disposition: attachment; filename="' . $downloadfilename . '"', __FILE__, __LINE__);
+            header('Content-Disposition: attachment; filename="' . $downloadfilename . '"');
+        } else {
+            $this->DebugMessage('SendSaveAsFileHeaderIfNeeded() sending header: Content-Disposition: inline; filename="' . $downloadfilename . '"', __FILE__, __LINE__);
+            header('Content-Disposition: inline; filename="' . $downloadfilename . '"');
         }
```
Comment (smg6511) [inline core/src/Revolution/modPhpThumb.php]: Consider this alternative, which keeps the code more concise (like it originally was) but improves readability like you were going for:
```suggestion
        $inlineFilename = $_GET['sia'] ?? false;
        $attachmentFilename = $_GET['down'] ?? false;
        if ($inlineFilename || $attachmentFilename) {
            $filename = $inlineFilename ? $inlineFilename : $attachmentFilename ;
            $filename = phpthumb_functions::SanitizeFilename($filename);
        } else {
            $filename = 'phpThumb_generated_thumbnail' . ($_GET['f'] ?? 'jpg');
        }
        if ($filename) {
            $disposition = $attachmentFilename ? 'attachment' : 'inline' ;
            $this->DebugMessage('SendSaveAsFileHeaderIfNeeded() sending header: Content-Disposition: ' . $disposition . '; filename="' . $filename . '"', __FILE__, __LINE__);
            header('Content-Disposition: ' . $disposition . '; filename="' . $filename . '"');
        }
```

**Review by smg6511 — COMMENTED** [review]
Ok, so the issue stems from the fact that, beginning with php 8.0, certain errors can not be suppressed with the @ prefix. So, this PR does the right thing by replacing the suppression with `isset` tests, and I can confirm it does the job. I'm throwing a couple suggestions for conciseness and clarity, but they aren't blockers to approval. Please respond one way or another and I'll provide approval afterward.

**Comment by Mark-H** [comment]
Thanks for making your first contribution @jolichter! :) 

Solid suggestions from @smg6511 that I'd like to second, and fwiw those code quality issues flagged by phpcs (at least the ones in red) will also need to be addressed before this can be merged. 

We're looking to release 3.0.3 next week, would be great to get this in, but it could use some minor tweaks. Do you think you'd be able to implement those in the coming days @jolichter or would you need some help with that?

**Comment by jolichter** [comment]
Thanks @Mark-H and @smg6511 !

I've updated to MODX 3.0.3-pl and changed the better suggestion of smg6511 in my 'modPhpThumb.php'. The suggestion works without problems and no error like 'HTTP_IF_MODIFIED_SINCE',  'sia' or 'down' appears. I hope I implemented this correctly and it will be included in the upcoming update? If not, I probably need your support.

PS: I would have it simple mark as resolve? Sorry  @smg6511
PS2: I resolved it (it is new for me to participate in such a big project)

**Comment by JoshuaLuckers** [comment]
Once the PR is merged the issue will be marked as solved! 

Thanks for taking time to help make MODX better!

**Review by Mark-H — APPROVED** [review]

**Review by smg6511 — APPROVED** [review]

**Comment by modxcommunity** [comment]
This pull request has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/3-0-3-change-document-to-collection-no-content-anymore/6403/7
