### PR TITLE
Mark modX::parseChunk as deprecated (#12433)

### LINKED ISSUE #12433: parseChunk does not give precedence to values passed in
### Summary

When passing an associative `array` to `$modx->parseChunk()`, the values parsed in are not given priority processing order, and therefore are not always honored if you have a conflicting, preexisting placeholder set before it.
### Step to reproduce
1. Create a Plugin (`OnWebPageInit`) that sets a placeholder on each request:
   
   ``` php
   $modx->setPlaceholder('example', 'ABC' );
   ```
2. Create a Chunk (example) that outputs the placeholder:
   
   ``` html
   Example: [[+example]]
   ```
3. Create and run a Snippet, invoking `parseChunk`, but with custom values:
   
   ``` php
   return $modx->parseChunk( 'example', array( 'example' => 'XYZ' ) );
   ```
### Observed behavior

Output = Example: **ABC**

The `parseChunk` method calls `getChunk` resulting in the conflicting placeholder being merged _first_, prior to parsing the `array` values provided.
### Expected behavior

Output = Example: **XYZ**
### Environment

MODX 2.3.4-dev

### PR DESCRIPTION
**Pull request by Mark-H**
### What does it do?

Marks modX::parseChunk as deprecated to discourage its use, targeting removal with the next batch of breaking changes, in 4.0.

### Why is it needed?
As discussed in #12433, parseChunk doesn't behave how one would expect it to, and is a lesser alternative to getChunk. That means we're better off without it, however we can't just remove it out-right.

### How to test
Not applicable.

### Related issue(s)/PR(s)
Fixes #12433

### CODE REVIEW

**Review by alroniks — APPROVED** [review]

File: core/src/Revolution/modX.php [hunk 1]
```diff
@@ -1954,8 +1954,10 @@ public function getChunk($chunkName, array $properties= []) {
      * @param string $prefix The placeholder prefix, defaults to [[+.
      * @param string $suffix The placeholder suffix, defaults to ]].
      * @return string The processed chunk with the placeholders replaced.
+     * @deprecated Prefer using $modx->getChunk, to be removed in MODX 4.0.
```
Comment (JoshuaLuckers) [inline core/src/Revolution/modX.php:1957]: Shouldn't this mention the "deprecated since release"?

**Review by JoshuaLuckers — APPROVED** [review]
