### PR TITLE
Menu improvements

### LINKED ISSUE #15386: MODX3: Menu item sorting does not work
### Summary
In https://github.com/modxcms/revolution/pull/15230 I added a parameter `ddAppendOnly: true` to the script, this prevented the menu items from being dragged behind the main menu areas (Main Navigation and User Navigation).

It was necessary because when dragging, the menu item could disappear from the main menu, which is not correct.

menu_dd_1

**But this parameter, apparently, also participates in the sorting of menu items.**

### Step to reproduce
Try changing the sorting in the menu settings.

### Expected behavior
In general, a solution is needed that would prohibit dragging the menu item outside of the main areas (Main Navigation and User Navigation), but would also enable drag-and-drop sorting.

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/pull/15230

### Environment
MODX 3

### PR DESCRIPTION
**Pull request by theboxer**
### What does it do?
- Hides the menu root (Main Menu) - we don't really need it
- Prevents dropping menu items outside of `Main Navigation` or `User Navigation`
- Prevents dragging/editing/deleting `Main Navigation` and `User Navigation`
- Adds context menu `Create Menu` on all nodes

### Why is it needed?
To prevent menu items from disappearing.

### How to test
Play with menus ;)

### Related issue(s)/PR(s)
#15386, #15230, #14521

### CODE REVIEW

**Review by Ruslan-Aleev — APPROVED** [review]
Thanks, it works!

mm

File: core/src/Revolution/Processors/System/Menu/GetNodes.php [hunk 1]
```diff
@@ -102,6 +102,11 @@ public function prepareRow(xPDOObject $object)
             'data' => $object->toArray(),
             'qtip' => strip_tags($desc),
         ];
+
+        if (empty($object->parent)) {
+            $objectArray['draggable'] = false;
+        }
```
Comment (mishanthrop) [inline core/src/Revolution/Processors/System/Menu/GetNodes.php]: Instead of these three lines, you can write above like this::
```php
'draggable' => !empty($object->parent),
```

File: manager/assets/modext/widgets/system/modx.tree.menu.js [hunk 2]
```diff
@@ -35,6 +34,24 @@ MODx.tree.Menu = function(config) {
 Ext.extend(MODx.tree.Menu, MODx.tree.Tree, {
     windows: {}
 
+    ,_handleDrop: function (dropEvent) {
+        var node = dropEvent.target;
+        if (node.isRoot) return false;
+
+        if ((dropEvent.point === 'above') || dropEvent.point === 'below') {
```
Comment (mishanthrop) [inline manager/assets/modext/widgets/system/modx.tree.menu.js]: unnecessary parentheses

```javascript
if (dropEvent.point === 'above' || dropEvent.point === 'below') {
```

**Review by Ibochkarev — APPROVED** [review]
I confirm - it works. Thank you =)
