### PR TITLE
Fix empty files not being clickable in the file tree (#15976)

### LINKED ISSUE #15976: MODX does not allow you to create/open an empty file
### Summary
MODX does not allow you to create/open an empty file, even if the file is not created through the CMS.

### Step to reproduce
Try to create an empty txt file and save it.

emptyFile

If you create an empty file on the server, then MODX will display the file in the tree, but will not allow you to open it.

### Environment
MODX 3.0.0-rc1

### PR DESCRIPTION
**Pull request by Mark-H**
### What does it do?

- Adds a debug log statement so we can inspect the mime types of files more easily in the future
- Considers application/x-empty as a non-binary file type
- Fixes `PHP warning: Undefined array key "Orientation"` warning for each image in the tree lacking that Exif header

### Why is it needed?
Fix empty files not being clickable in the file tree, due to unrecognised application/x-empty mime type

### How to test
https://github.com/modxcms/revolution/pull/15977#issuecomment-1018613790

### Related issue(s)/PR(s)
Fixes #15976 (again)

### CODE REVIEW

File: core/src/Revolution/Sources/modMediaSource.php [hunk 1]
```diff
@@ -2331,6 +2331,7 @@ protected function isFileBinary($file)
     {
         try {
             $mime = $this->filesystem->mimeType($file);
+            $this->xpdo->log(xPDO::LOG_LEVEL_DEBUG,$file . ' has a mime type of: ' . $mime);
```
Comment (JoshuaLuckers) [inline core/src/Revolution/Sources/modMediaSource.php]:
```suggestion
            $this->xpdo->log(xPDO::LOG_LEVEL_DEBUG, $file . ' has a mime type of: ' . $mime);
```

**Comment by muzzwood** [comment]
Just tested this. It works for me 👍🏻

**Review by JoshuaLuckers — APPROVED** [review]
