### PR TITLE
Fix undefined index in modMediaSource

### LINKED ISSUE #15499: PHP notice: Undefined index: src
### Summary
Log error:

```
[2021-03-06 13:34:06] (WARN @ /Users/bochkarev/Sites/bughunt/core/src/Revolution/Sources/modMediaSource.php : 1920) PHP notice: Undefined index: src
```

### Step to reproduce
Set system setting `log_level` to 4

Go to Media, then select Media browser

### Observed behavior
```
[2021-03-06 13:34:06] (WARN @ /Users/bochkarev/Sites/bughunt/core/src/Revolution/Sources/modMediaSource.php : 1920) PHP notice: Undefined index: src
```

The same behavior is observed when creating a new folder in the assets directory (for example)

### Expected behavior
There should be no errors in the log

### Related issue(s)/PR(s)
NA

### Environment
MODX Revolution 3.0.0-alpha3 (git), PHP Version 7.4.12

### PR DESCRIPTION
**Pull request by theboxer**
### What does it do?
Checks if the index exists

### Why is it needed?
Accessing array index that's not defined

### How to test
Described in #15499

### Related issue(s)/PR(s)
Resolves #15499

### CODE REVIEW

File: core/src/Revolution/Sources/modMediaSource.php [hunk 1]
```diff
@@ -1969,7 +1969,6 @@ protected function buildFileBrowserViewList($path, $ext, $image_extensions, $bas
         if ($this->visibility_files && $visibility) {
             $file_list['visibility'] = $visibility;
         }
-        $file_list['menu'] = $this->getListFileContextMenu($path, !empty($page));
```
Comment (Jako) [inline core/src/Revolution/Sources/modMediaSource.php:1972]: Is this line in use?

Comment (theboxer) [reply core/src/Revolution/Sources/modMediaSource.php:1972]: It's duplicate of line 1967

Comment (Jako) [reply core/src/Revolution/Sources/modMediaSource.php:1972]: Ok, fine.

**Review by Jako — APPROVED** [review]

**Review by Mark-H — APPROVED** [review]
